CREATE TABLE 'USER' (
    'USERID' INT NOT NULL AUTO_INCREMENT,
    'USERNAME' VARCHAR(45) ,
    'PASSWORD_HASH' VARCHAR(64) ,
    'PASSWORD_SALT' CHAR(32),
    'EMAIL' VARCHAR(45),
    'USERTYPE' VARCHAR(45) DEFAULT 'STUDENT',
    'DATE_OF_BIRTH' DATE DEFAULT NULL,
    'ADDRESS' VARCHAR(50) DEFAULT NULL,
    'PHONENUMBER' VARCHAR(15) DEFAULT NULL,
    'GENDER' VARCHAR(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL,
    'FULLNAME' VARCHAR(20) DEFAULT NULL,
    'AVATAR' VARCHAR(150) DEFAULT 'https://drive.google.com/thumbnail?id=1CMew23JedgSH1qOuT0K6jIscj-VRcwEC',
    PRIMARY KEY (USERID)
)